### ISSUE TITLE
How to style Outside days of month?

### ISSUE THREAD

**Issue by digitaldirk** [danheron/Heron.MudCalendar#187]
By following the extending example I was able to override Cell Days to add a button and style the day number text with the Outside bool property.

I would now like to have the entire day box of month view be stylied if it is Outside the current month. Is there a built in way to do this?

Thank you

**Comment by danheron** [comment]
You would override RenderCellContainer instead of RenderCellDayNumber.

Look at MonthView.razor in the source code (look in the main branch not dev branch).  Copy the existing method to use as a starting point.

However the Month View has been completely rewritten.  The changes you make now will not work when the next version is released.  So you might want to wait before doing anything.

**Comment by digitaldirk** [comment]
Thank you for the information 👍@danheron
