### ISSUE TITLE
DatePicker does not update Calendar

### ISSUE THREAD

**Issue by TDroogers** [danheron/Heron.MudCalendar#2]
Hi, I like this extension :)

But I found a bug, when you change month with the DatePicker the Calender is not updated.
And when you change month with the arrows the DatePicker is not updated.

And also a future request, can you make it possible to hide the date picker and some views (month/week/day)?  

![2023-03-10_09h43_58](https://user-images.githubusercontent.com/34547552/224267909-79ea4382-c4e5-44ed-91d7-8f671d4ae9c2.gif)

I can not compile your project. It can not find `using MudBlazor.Docs.Extensions;`
![afbeelding](https://user-images.githubusercontent.com/34547552/224268708-0675fd09-0b29-44fb-a1dc-acdb181f9404.png)

**Comment by danheron** [comment]
Thanks for reporting the bug, I will take a look at it.

There are already properties to hide views you don't want.  e.g. If you don't need the day view you can set ShowDay = false.

You should be able to compile the MudCalendar project.  To compile the whole solution you need MudBlazor as well because the Docs use MudBlazor.Docs.

I have a fork of MudBlazor in my github.  To compile the whole solution you need to clone this repo and checkout the mudcalendar branch.  Your file structure should look like:

MyProjects
    | -> MudBlazor
    | -> Heron.MudCalendar

**Comment by TDroogers** [comment]
I have the same file structure, but had never build MudBlazor in release. After doing that it did compile!

I somehow mist those ShnowDay, but is there also an option to hide the DatePicker?

**Comment by danheron** [comment]
There isn't currently an option to show/hide DatePicker, but I will add one.

**Comment by TDroogers** [comment]
Thanks!
