### ISSUE TITLE
DateRangeChanged callback

### ISSUE THREAD

**Issue by ryannicholls-dev** [danheron/Heron.MudCalendar#71]
Firstly, thank you for a great component!

I have a quick query/issue that I'm wondering if you could please take a look at. If I am viewing the calendar for today's date (08/11/23), and press the back button to switch to October, the StartDate in the DateRange object is 25/09/23 which makes it difficult to filter my bookings by the month of October. I wouldn't be interested in the September bookings in this instance. The idea would be for me to only retrieve bookings for the month visible (aka October) so I could send all bookings out on a month by month basis. 

Thank you.

**Comment by danheron** [comment]
It works like that because when you view October you can see the last 6 days of September and the first 5 days of November.  It's normal for calendars to show bookings for all days that are visible.

There is another issue open #70 to add a CurrentDayChanged event.  When I make this change you will be able to subscribe to this event and use the month of the CurrentDay.

**Comment by danheron** [comment]
Closing because the CurrentDayChanged event has been added in the latest release.
